llm:
  provider: openai
  model: grok-2-latest
  base_url: https://api.x.ai/v1/chat/completions
  api_key: ${BIDDING_ASSISTANT_LLM_API_KEY:-dummy}
  timeout: 60
retrieval:
  enable_heuristic: true
  enable_embedding: false
  limit: 6
